CC:=g++

sourcedir:=source
headerdir:=header
objectdir:=object
dependdir:=depend
binarydir:=binary

debugdir:=debug
releasedir:=release
defaultdir:=
coverdir:=$(debugdir)

sourceextension:=.cc

# -s flag strips symbols
# not doing this allows a 'client' to run a `gdb main` `bt`
#   which could be useful
defaultflags:= -Wall -Wextra -pedantic -std=c++17 -I./$(headerdir) -I./catch/include
releaseflags:= $(defaultflags) -O2 -s
debugflags:= $(defaultflags) -DDEBUG -ggdb3
coverflags:= $(debugflags) --coverage

name:=main

builds:=default debug release cover

all:debug release

docs:documentation/html/index.html

documentation/html/index.html:header/*.hh source/*.cc
	doxygen doxygen.doxyfile

#TODO:investigate using -fbranch-probabilities
#website appears to be a useful resource:
#  alex.dzyoba.com/linux/profiling-gprof-gcov.html
#  gcovr.com/guide.html

