CC:=g++

sourcedir:=source
headerdir:=header
objectdir:=object
dependdir:=depend
binarydir:=binary

debugdir:=debug
releasedir:=release
defaultdir:=
coverdir:=$(debugdir)

sourceextension:=.cc

# -s flag strips symbols
# not doing this allows a 'client' to run a `gdb main` `bt`
#   which could be useful
defaultflags:= -Wall -Wextra -pedantic -std=c++14 -I./$(headerdir)
releaseflags:= $(defaultflags) -O2 -s
debugflags:= $(defaultflags) -DDEBUG -ggdb3
coverflags:= $(debugflags) --coverage

name:=main

builds:=default debug release cover

all:debug release

#TODO:investigate using -fbranch-probabilities
#website appears to be a useful resource:
#  alex.dzyoba.com/linux/profiling-gprof-gcov.html

