#!/usr/bin/env bash

exec 3<>/dev/tcp/google.com/80

lines=(
  'GET /ping HTTP/1.1'
  'Host: google.com'
  'Connection: close'
  ''
)

printf '%s\r\n' "${lines[@]}" >&3

while read -r data <&3; do
  echo "Server response: $data"
done

exec 3>&-
