#pragma once

#include <cstddef>

namespace flp::Random {

// w - the power of two that determines the range of values generated by the engine
// n - the degree of recurrence
// m - the middle word, an offset used in the recurrence relation defining the state
// r - the number of bits of the lower bit-mask, also known as the twist value
// a - the conditional xor-mask, i.e. the coefficients of the rational normal form twist matrix
// u, d, s, b, t, c, l - the 1st to 7th components of the bit-scrambling (tempering) matrix
// f - the initialization multiplier

template<
  typename Type,
  size_t w,
  size_t n,
  size_t m,
  size_t r,
  Type a,
  size_t u,
  Type d,
  size_t s,
  Type b,
  size_t t,
  Type c,
  size_t l,
  Type f
>
struct MersenneTwister {
  using Result = Type;
};

using MT19937 = MersenneTwister<size_t,
  64, 312, 156, 31,
  0xb5026f5aa96619e9, 29,
  0x5555555555555555, 17,
  0x71d67fffeda60000, 37,
  0xfff7eee000000000, 43,
  6364136223846793005
>;

}
