#!/usr/bin/env bash

source ./lib/bmp.bash || exit

debug() {
  echo '[debug]' "$@" >&2
}

make-bmp() {
  local SPRITE
  mapfile -t SPRITE

  local width=${#SPRITE[0]}
  local height=${#SPRITE[@]}

  bmp-header "$width" "$height"
  local padding="$REPLY"

  local r g b x y
  for ((y = 0; y < height; y++)); do
    for ((x = 0; x < width; x++)); do
      local c=${SPRITE[height - y - 1]}
      c=${c:x:1}

      read -r r g b <<< "${PALETTE[$c]}"
      rgb "$r" "$g" "$b"
    done
    bmp-pad "$padding"
    debug "$y/$height" # progress bar?
  done
}

hex2rgb() {
  local hex=${1#\#}

  local r=$((16#${hex:0:2}))
  local g=$((16#${hex:2:2}))
  local b=$((16#${hex:4:2}))

  echo "$r" "$g" "$b"
}

load-palette() {
  local file="$1"
  local lines
  mapfile -t lines < "$file" || exit
  local line
  for line in "${lines[@]}"; do
    local c hex
    c=${line:0:1}
    hex=${line:2}

    PALETTE[$c]=$(hex2rgb "$hex")
  done
}

Main() {
  local output="out.bmp"

  local palette
  local OPTIND OPTARG opt
  while getopts 'p:o:' opt; do
    case "$opt" in
      o) output="$OPTARG";;
      p) palette="$OPTARG";;
    esac
  done

  [[ -n $palette ]] || exit
  load-palette

  echo "writing image to $output"
  make-bmp > "$output" || exit
  echo "Wrote image to $output"
}



Main $@
unset Main
