#pragma once

namespace flp {

struct Measure {
  using Type = signed long long;

  Type length;
  Type time;
  Type mass;
  Type current;
  Type temperature;
  Type candela;
  Type money;
  Type angle;
  Type percentage;
  Type count;
  Type byte;
  Type tick;

  constexpr Measure inverse() const {
    return {
      -length, -time, -mass, -current, -temperature, -candela, -money, -angle, -percentage, -count, -byte, -tick
    };
  }

  constexpr friend Measure operator*(const Measure& lhs, const Measure& rhs) {
    return Measure { .length      = lhs.length + rhs.length,
                     .time        = lhs.time + rhs.time,
                     .mass        = lhs.mass + rhs.mass,
                     .current     = lhs.current + rhs.current,
                     .temperature = lhs.temperature + rhs.temperature,
                     .candela     = lhs.candela + rhs.candela,
                     .money       = lhs.money + rhs.money,
                     .angle       = lhs.angle + rhs.angle,
                     .percentage  = lhs.percentage + rhs.percentage,
                     .count       = lhs.count + rhs.count,
                     .byte        = lhs.byte + rhs.byte,
                     .tick        = lhs.tick + rhs.tick };
  }

  constexpr friend Measure operator/(const Measure& lhs, const Measure& rhs) {
    return Measure { .length      = lhs.length - rhs.length,
                     .time        = lhs.time - rhs.time,
                     .mass        = lhs.mass - rhs.mass,
                     .current     = lhs.current - rhs.current,
                     .temperature = lhs.temperature - rhs.temperature,
                     .candela     = lhs.candela - rhs.candela,
                     .money       = lhs.money - rhs.money,
                     .angle       = lhs.angle - rhs.angle,
                     .percentage  = lhs.percentage - rhs.percentage,
                     .count       = lhs.count - rhs.count,
                     .byte        = lhs.byte - rhs.byte,
                     .tick        = lhs.tick - rhs.tick };
  }
};

constexpr Measure NoneMeasure           = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure LengthMeasure         = { .length      = 1,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure MassMeasure           = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 1,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure CurrentMeasure        = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 1,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure TemperatureMeasure    = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 1,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure LightIntensityMeasure = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 1,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure MoneyMeasure          = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 1,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure TimeMeasure           = { .length      = 0,
                                            .time        = 1,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure TickMeasure           = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 1,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure PercentMeasure        = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 1,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure FrequencyMeasure      = { .length      = 0,
                                            .time        = -1,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure AngleMeasure          = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 1,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure SolidAngleMeasure     = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 2,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure MoleMeasure           = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 1,
                                            .tick        = 0 };
constexpr Measure ByteMeasure           = { .length      = 0,
                                            .time        = 0,
                                            .mass        = 0,
                                            .current     = 0,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 1 };
constexpr Measure VoltageMeasure        = { .length      = 2,
                                            .time        = -3,
                                            .mass        = 1,
                                            .current     = -1,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure ResistanceMeasure     = { .length      = 2,
                                            .time        = -3,
                                            .mass        = 1,
                                            .current     = -2,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure CapacitanceMeasure    = { .length      = -2,
                                            .time        = 4,
                                            .mass        = -1,
                                            .current     = 2,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure InductanceMeasure     = { .length      = 2,
                                            .time        = -2,
                                            .mass        = 1,
                                            .current     = -2,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure ChargeMeasure         = { .length      = 0,
                                            .time        = 1,
                                            .mass        = 0,
                                            .current     = 1,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure MagneticFieldMeasure  = { .length      = 0,
                                            .time        = -2,
                                            .mass        = 1,
                                            .current     = 1,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };
constexpr Measure ElectricFieldMeasure  = { .length      = 1,
                                            .time        = -3,
                                            .mass        = 1,
                                            .current     = -1,
                                            .temperature = 0,
                                            .candela     = 0,
                                            .money       = 0,
                                            .angle       = 0,
                                            .percentage  = 0,
                                            .count       = 0,
                                            .byte        = 0,
                                            .tick        = 0 };

} // namespace flp
